Local songs album covers
MarcoPNS/Spotify-Stream-Widget pull request #34
Opened 2020-10-09 00:52 UTC by wong-justin

### This is an addition to show cover images for local songs played through Spotify.

Spotify plays local songs and can incorporate them into playlists when the user adds them
(desktop Spotify -> Edit -> Preferences... -> Local Files -> Add A Source),
and when requested, the Spotify Web API will give main info like title and artist.
However, the cover image is not given (because it is not on Spotify servers).
[Example Local Song Spotify Response](https://developer.spotify.com/documentation/general/guides/local-files-spotify-playlists/)
The default backup image in /Resources will be shown in the widget.

This pull request amends that through a LocalSongManager class that reads audio file metadata in the local file directory. It requires the package TagLibSharp.

Local songs are probably a pretty small use case among users, but maybe someone else besides me would benefit too.
Hopefully the code style/structure fits the project since I've never contributed before.

Screenshots:

![SettingsWithLocalSongsControls_blurred](https://user-images.githubusercontent.com/28441593/95528852-45319d80-09a7-11eb-9136-d9ebff8bb2aa.png)

![LocalSongCoverDisplayed](https://user-images.githubusercontent.com/28441593/95529095-0c45f880-09a8-11eb-8646-129c24456448.JPG)

2020-10-10 08:11 UTC, MarcoPNS requested changes
First of all: Thank you for your PR! It's well written. I would like to do some testing and maybe switch to async before going live with this feature. Also it seems that you missed the `My.Settings` section.

2020-10-10 08:11 UTC, MarcoPNS commented on Spotify Stream Widget/LocalSongManager.vb
> +        For Each filepath In IO.Directory.GetFiles(dir, "*.*").Where(Function(f) IsAudio(f))
Does not work recursive. `System.IO.SearchOption.AllDirectories should fix` this.

2020-10-10 08:11 UTC, MarcoPNS commented on Spotify Stream Widget/LocalSongManager.vb
> +    End Sub
Probably blocks the UI for a few seconds - would like to test it with a HUGE Folder. Should be async for final release.

2020-10-10 08:11 UTC, MarcoPNS commented on Spotify Stream Widget/Viewer.vb
> +                AlbumCover.Image = _localSongManager.ImageForSong(_playback.Item.Name, _playback.Item.Artists(0).Name)
maybe check if the localSongManager is not nothing.

2020-10-11 03:42 UTC, wong-justin commented
Thanks for the feedback! I addressed the things you mentioned except for async. Anything else needing work before that?

2021-04-05 11:59 UTC, merged